name: Django CI

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code1
      uses: actions/checkout@v3


    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: SSH CONNECT
      run: |
        ssh -o StrictHostKeyChecking=no root@1117af62369e.vps.myjino.ru -p 49209 << 'EOF'
          # ssh -p 49209 -o StrictHostKeyChecking=no root@1117af62369e.vps.myjino.ru << 'EOF'
        EOF

    - name: Copy files to VM
      run: |
        # cd tracker
        
        scp -P 49209 docker-compose.yml root@1117af62369e.vps.myjino.ru:~/tracker/ 
        scp -P 49209 nginx.conf root@1117af62369e.vps.myjino.ru:~/tracker/
        scp -P 49209 deploy/Dockerfile root@1117af62369e.vps.myjino.ru:~/tracker/ 

      shell: bash

    - name: Create .env
      run: |
        ssh -o StrictHostKeyChecking=no root@1117af62369e.vps.myjino.ru -p 49209 << 'EOF'
          cd tracker
          sudo rm -r .env
          echo '${{ secrets.ENV }}' >> .env
        EOF
        
             
         
          

    - name: Start Docker
      run: |
        ssh -o StrictHostKeyChecking=no root@1117af62369e.vps.myjino.ru -p 49209 "
          cd tracker && \
          # sudo docker system prune -af && \
          # sudo docker volume prune -f && \
          # sudo docker compose -f docker-compose.yml down --remove-orphans && \

          sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:04e74c1925eed3fda3bb9f31f24d6c7b882422a9
          # ${{ github.sha }}  && \
          
          sudo docker run -d --name myapp -p 80:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:04e74c1925eed3fda3bb9f31f24d6c7b882422a9
        # && \
        
          sudo docker compose -f docker-compose.yml up -d --build
        
        "

