name: Django CI

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code1
      uses: actions/checkout@v3


    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: SSH CONNECT
      run: |
        ssh -o StrictHostKeyChecking=no root@1117af62369e.vps.myjino.ru -p 49209 << 'EOF'
          # ssh -p 49209 -o StrictHostKeyChecking=no root@1117af62369e.vps.myjino.ru << 'EOF'
        EOF

    - name: Copy files to VM
      run: |
        # cd tracker
        ls
        scp -P 49209  docker-compose.yml  root@1117af62369e.vps.myjino.ru:~/tracker/ 
        scp -P 49209 deploy/Dockerfile   root@1117af62369e.vps.myjino.ru:~/tracker/ 

      shell: bash

    - name: Create .env
      run: |
        ssh -o StrictHostKeyChecking=no root@1117af62369e.vps.myjino.ru -p 49209 << 'EOF'
          cd tracker
          ls
          sudo rm -r .env
          echo '${{ secrets.ENV }}' >> .env
        EOF
        
      

        
         
          

    - name: error Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
          cd tracker && \
          sudo docker system prune -af && \
          sudo docker volume prune -f && \
          sudo docker compose -f docker-compose.yaml down --remove-orphans && \

          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}  && \
          
          docker run -d --name myapp -p 80:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}  && \
        
          sudo docker compose -f docker-compose.yaml up -d --build
        
        "

